[package]
name = "LibraryProject"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
actix-cors = "0.6"


[[bin]]
name = "LibraryProject"
path= "app.rs"
